[workspace]
members = ["kvx", "kvx-macros", "kvx-types"]
resolver = "2"

[workspace.package]
version = "0.9.3"
edition = "2021"
license = "BSD-3-Clause"
repository = "https://github.com/nlnetlabs/kvx"
