name: Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: cargo-

      - run: rustup toolchain install stable --profile minimal
      - run: |
          cargo check --all-features --tests
          cargo clippy --all-features --tests -- -D warnings
          cargo build --release --all-features --verbose

  check-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: nightly-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: nightly-

      - run: rustup toolchain install nightly --profile minimal
      - run: rustup component add rustfmt
      - run: cargo install cargo-udeps || true
      - run: |
          cargo +nightly fmt --check
          cargo +nightly udeps --all-features --all-targets
